#!/bin/sh

# disable if go-carbon enabled
[[ -n "${GOCARBON}" ]] && exit 1

[[ -f "./down" ]] && exit 1

if [ -n "${CARBON_DISABLE_TAGS}" ]; then
    # trying to disable tags in carbon.conf file
    sed -i 's/ENABLE_TAGS = True/ENABLE_TAGS = False/g' /opt/graphite/conf/carbon.conf
fi

exec python3 /opt/graphite/bin/carbon-cache.py start --debug 2>&1
