#!/bin/sh

[[ -n "${BRUBECK}" ]] && exit 1

if folder_empty /opt/statsd/config/; then
	cp /opt/defaultconf/statsd/config/*.js /opt/statsd/config/
fi

exec node /opt/statsd/stats.js /opt/statsd/config/$STATSD_INTERFACE.js 2>&1
