#!/bin/sh

if folder_empty /opt/statsd/config/; then
	cp /opt/defaultconf/statsd/config/*.js /opt/statsd/config/
fi

exec node /opt/statsd/stats.js /opt/statsd/config/$STATSD_INTERFACE.js 2>&1 | tee -a /var/log/statsd.log
