#!/bin/sh

[[ -f "./down" ]] && exit 1

if folder_empty /var/log/graphite; then
	mkdir -p /var/log/graphite
	touch /var/log/syslog
fi

if folder_empty /opt/graphite/conf; then
	cp /opt/defaultconf/graphite/*.conf /opt/graphite/conf/
fi

if folder_empty /opt/graphite/webapp/graphite; then
	cp /opt/defaultconf/graphite/local_settings.py /opt/graphite/webapp/graphite/local_settings.py
fi

if folder_empty /opt/graphite/storage; then
	mkdir -p /opt/graphite/storage/whisper
fi

export PYTHONPATH=/opt/graphite/webapp
export DJANGO_SETTINGS_MODULE=graphite.settings
/opt/graphite/bin/django-admin.py makemigrations
/opt/graphite/bin/django-admin.py migrate auth
/opt/graphite/bin/django-admin.py migrate --run-syncdb
/opt/graphite/bin/django_admin_init.sh || true

if folder_empty /opt/graphite/webapp/graphite/functions/custom; then
	touch /opt/graphite/webapp/graphite/functions/custom/__init__.py
fi

export GRAPHITE_WSGI_PROCESSES=${GRAPHITE_WSGI_PROCESSES:-4}
export GRAPHITE_WSGI_THREADS=${GRAPHITE_WSGI_THREADS:-1}
export GRAPHITE_WSGI_REQUEST_TIMEOUT=${GRAPHITE_WSGI_REQUEST_TIMEOUT:-65}
export GRAPHITE_WSGI_REQUEST_LINE=${GRAPHITE_WSGI_REQUEST_LINE:-0}
export GRAPHITE_WSGI_MAX_REQUESTS=${GRAPHITE_WSGI_MAX_REQUESTS:-1000}
export GRAPHITE_WSGI_WORKER_CLASS=${GRAPHITE_WSGI_WORKER_CLASS:-"sync"}
export GRAPHITE_WSGI_WORKER_CONNECTIONS=${GRAPHITE_WSGI_WORKER_CONNECTIONS:-1000}
if [ "${GRAPHITE_WSGI_WORKER_CLASS}" == "gevent" ]; then
    export GUNICORN_EXTRA_PARAMS="--worker-connections=${GRAPHITE_WSGI_WORKER_CONNECTIONS} "
else
    export GUNICORN_EXTRA_PARAMS="--preload --threads=${GRAPHITE_WSGI_THREADS} "
fi

# start nginx if not disabled
[[ -f "/etc/service/nginx/down" ]] || sv start nginx || exit 1

exec /opt/graphite/bin/gunicorn wsgi --pythonpath=/opt/graphite/webapp/graphite \
    ${GUNICORN_EXTRA_PARAMS} \
    --worker-class=${GRAPHITE_WSGI_WORKER_CLASS} \
    --workers=${GRAPHITE_WSGI_PROCESSES} \
    --limit-request-line=${GRAPHITE_WSGI_REQUEST_LINE} \
    --max-requests=${GRAPHITE_WSGI_MAX_REQUESTS} \
    --timeout=${GRAPHITE_WSGI_REQUEST_TIMEOUT} \
    --bind=0.0.0.0:8080 \
    --log-file=/var/log/gunicorn.log
