#!/bin/bash

sv start nginx || exit 1
source /opt/graphite/bin/activate
export PYTHONPATH=/opt/graphite/webapp && exec /opt/graphite/bin/gunicorn wsgi --workers=4 --bind=0.0.0.0:8080 --log-file=/var/log/gunicorn.log --preload --pythonpath=/opt/graphite/webapp/graphite
