#!/usr/bin/env expect

set timeout -1
spawn python /opt/graphite/webapp/graphite/manage.py syncdb

expect "Would you like to create one now" {
  send "yes\r"
}

expect "Username *:" {
  send "admin\r"
}

expect "E-mail address:" {
  send "admin@admin.com\r"
}

expect "Password:" {
  send "admin-secret\r"
}

expect "Password *:" {
  send "admin-secret\r"
}

expect "Superuser created successfully"

